In [7]:

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [15]:
data = pd.read_csv("sustainability_data.csv")

In [9]:
X = data[['Energy_Consumption','Renewable_Percentage','GDP']]
y = data['CO2_Emissions']

In [17]:
data.head()

   Year  Energy_Consumption  Renewable_Percentage   GDP  CO2_Emissions
0  2000                 517             13.823292   985     816.163479
1  2001                 516             24.170636  1334     869.155993
2  2002                 468             28.369161  1604     883.858124
3  2003                 531             19.401217  1668     947.372230
4  2004                 483             26.920520  1254     837.837492

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
 poly = PolynomialFeatures(degree=2)
 X_poly_train=poly.fit_transform(X_train)
 X_poly_test = poly.transform(X_test)

In [22]:
model = LinearRegression()
model.fit(X_poly_train,y_train)
y_pred = model.predict(X_poly_test)

In [23]:
print(y_pred)

[ 738.71819215  876.20207775  946.93960302  859.7421646  1012.25811808]

In [25]:
X_test

    Energy_Consumption  Renewable_Percentage   GDP
0                  517             13.823292   985
17                 571             27.546205  1296
15                 516             24.881291  1695
1                  516             24.170636  1334
8                  592             23.053935  1811

In [26]:
y_test

0     816.163479
17    891.688524
15    926.884054
1     869.155993
8     963.445540
Name: CO2_Emissions, dtype: float64

In [33]:
from sklearn.metrics import mean_squared_error,r2_score
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print(f'Meam Squared Error:{mse}')
print(f'R2 Score:{r2}')

Meam Squared Error:1822.2231123620822
R2 Score:0.27595996134777256